Feature/#136 create new enemy
vr-tower-defense/vr-tower-defense pull request #147
Opened 2019-05-22 08:19 UTC by DoctorDarius

2019-05-22 10:51 UTC, hassanAlAwwadi commented on src/Assets/LightSkyDefense/Scripts/Enemies/EnemySplit.cs
> +            leftSplitEnemy.gameObject.GetComponent<Damageable>().UpdateHealth(-0.6f);
Should damageable be a required component?

2019-05-22 10:53 UTC, mserier requested changes

2019-05-22 10:53 UTC, mserier commented on src/Assets/LightSkyDefense/Scripts/Enemies/EnemyAoEHeal.cs
> +        var i = 0;
Please use for loop

2019-05-22 10:56 UTC, hassanAlAwwadi commented on src/Assets/LightSkyDefense/Scripts/Enemies/EnemyAoEHeal.cs
> +        while (i < enemiesInRange.Length)
make for loop + {}

2019-05-22 11:11 UTC, leroykorterink requested changes

2019-05-22 11:11 UTC, leroykorterink commented on src/Assets/LightSkyDefense/Scripts/Enemies/EnemySplit.cs
> +            leftSplitEnemy.gameObject.GetComponent<Damageable>().UpdateHealth(-0.6f);
```suggestion
            leftSplitEnemy.GetComponent<Damageable>().UpdateHealth(-0.6f);
```

2019-05-22 11:11 UTC, leroykorterink commented on src/Assets/LightSkyDefense/Scripts/Enemies/EnemySplit.cs
> +            var leftSplitEnemy = Instantiate(
we should rename this to `newEnemy`.

2019-05-22 11:11 UTC, leroykorterink commented on src/Assets/LightSkyDefense/Scripts/Enemies/EnemyShoot.cs
> +    private void OnTriggerEnter(Collider target)
We should use `Physics.OverlapSphere` instead of a collider.

2019-05-22 11:11 UTC, leroykorterink commented on src/Assets/LightSkyDefense/Scripts/Enemies/EnemyShoot.cs
> +        yield return new WaitForSeconds(5);
Magic number?

2019-05-22 11:11 UTC, leroykorterink commented on src/Assets/LightSkyDefense/Scripts/Enemies/EnemyAoEHeal.cs
> +        if (enemiesInRange.Length < 1) return;
Not necessary to return since the while loop body won't be reached when `enemiesInRange` is < 1

2019-05-22 11:11 UTC, leroykorterink commented on src/Assets/LightSkyDefense/Scripts/Enemies/Enemy.cs
> +        GameObject.Find("Scoreboard").GetComponent<Scoreboard>().PointGain(PointValue);
We should use messages instead of hardcoded dependencies to track the player score

2019-05-22 11:11 UTC, leroykorterink commented on src/Assets/LightSkyDefense/Scripts/Towers/BaseTower.cs
> +    public void OnJam(float jamTime)
Add xmldoc please

2019-05-22 11:47 UTC, DoctorDarius commented on src/Assets/LightSkyDefense/Scripts/Towers/BaseTower.cs
> +    public void OnJam(float jamTime)
????

2019-05-24 19:39 UTC, leroykorterink commented
Closing this PR to fix its branch name

2019-05-24 19:39 UTC, closed without merging